<?php

namespace scrclub\CMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * categoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentTypeRepository extends EntityRepository
{
}
