<?php

namespace scrclub\CMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MediaSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaSetRepository extends EntityRepository
{
}
