<?php

namespace scrclub\CMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MediaDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaNodeRepository extends EntityRepository
{
}
