backend_post:
    pattern:  /
    defaults: { _controller: "scrclubCMSBundle:Post:index" }

backend_post_show:
    pattern:  /{id}/show
    defaults: { _controller: "scrclubCMSBundle:Post:show" }

backend_post_new:
    pattern:  /new
    defaults: { _controller: "scrclubCMSBundle:Post:new" }

backend_post_create:
    pattern:  /create
    defaults: { _controller: "scrclubCMSBundle:Post:create" }
    requirements: { _method: post }

backend_post_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "scrclubCMSBundle:Post:edit" }

backend_post_update:
    pattern:  /{id}/update
    defaults: { _controller: "scrclubCMSBundle:Post:update" }
    requirements: { _method: post }

backend_post_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "scrclubCMSBundle:Post:delete" }
    requirements: { _method: post }
